package net.optionfactory.spring.downstream.plugin.emit.ts;

import java.io.File;
import java.nio.file.Files;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import net.optionfactory.spring.downstream.plugin.emit.SourceEmitter.GenerateOutcome;
import net.optionfactory.spring.downstream.plugin.mapping.TypeRegistry;
import net.optionfactory.spring.downstream.plugin.mapping.TypeRegistry.Nesting;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

public class TypeScriptEmitterTest {

    public enum Empty {
    }

    public enum Status {
        ON, OFF
    }

    public static class Zebra {

        public Optional<String> nickname;
        public Status status;

        public static class Stripe {

            public int width;
        }
    }

    public static class Antelope {

        public String name;
    }

    @Test
    public void writesASingleSpecFileSortedByNameInAMissingDirectory(@TempDir File tempDir) throws Exception {
        final var outputDir = new File(tempDir, "not/yet/there");
        final var registry = new TypeRegistry(Set.of(Zebra.class, Antelope.class), "", Nesting.FLATTEN);
        final var outcomes = new TypeScriptEmitter(outputDir, Map.of(), Map.of()).emit(registry);

        Assertions.assertEquals(List.of(new GenerateOutcome("Antelope", true), new GenerateOutcome("Zebra", true)), outcomes, "every type is generated, sorted by package and simple name");
        final var content = Files.readString(new File(outputDir, "spec.d.ts").toPath());
        Assertions.assertTrue(content.startsWith("// Generated by downstream-maven-plugin\n"), "the spec starts with the generation banner");
        Assertions.assertTrue(content.indexOf("interface Antelope") < content.indexOf("interface Zebra"), "types are written in sorted order");
    }

    @Test
    public void enumsBecomeStringUnionsAndEmptyEnumsBecomeNever(@TempDir File tempDir) throws Exception {
        final var registry = new TypeRegistry(Set.of(Status.class, Empty.class), "", Nesting.FLATTEN);
        new TypeScriptEmitter(tempDir, Map.of(), Map.of()).emit(registry);

        final var content = Files.readString(new File(tempDir, "spec.d.ts").toPath());
        Assertions.assertTrue(content.contains("export type Status = \"ON\"\n    | \"OFF\";"), "enum constants become a union of string literals");
        Assertions.assertTrue(content.contains("export type Empty = never;"), "an enum without constants becomes never");
    }

    @Test
    public void optionalFieldsAreMarkedOptionalAndNestedTypesUseTheirFlatName(@TempDir File tempDir) throws Exception {
        final var registry = new TypeRegistry(Set.of(Zebra.class, Zebra.Stripe.class, Status.class), "", Nesting.NESTED);
        new TypeScriptEmitter(tempDir, Map.of(), Map.of()).emit(registry);

        final var content = Files.readString(new File(tempDir, "spec.d.ts").toPath());
        Assertions.assertTrue(content.contains("nickname?: string;"), "an Optional field is an optional property of its content type");
        Assertions.assertTrue(content.contains("status: Status;"), "a non optional field is a required property");
        Assertions.assertTrue(content.contains("export interface ZebraStripe {"), "with NESTED a nested type is emitted top-level, prefixed with its outer types");
    }

    @Test
    public void aliasesAreDeclaredBeforeTheTypes(@TempDir File tempDir) throws Exception {
        final var registry = new TypeRegistry(Set.of(Antelope.class), "", Nesting.FLATTEN);
        new TypeScriptEmitter(tempDir, Map.of(), Map.of("java.time.Instant", "string")).emit(registry);

        final var content = Files.readString(new File(tempDir, "spec.d.ts").toPath());
        Assertions.assertTrue(content.contains("export type Instant = string;\n\nexport interface Antelope"), "each alias is declared under the simple name of its java type, ahead of the types");
    }
}
