package net.optionfactory.spring.data.jpa.filtering.h2.filters.spi.paths;

import net.optionfactory.spring.data.jpa.filtering.FilterRequest;
import net.optionfactory.spring.data.jpa.filtering.h2.HibernateOnH2TestConfig;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.transaction.annotation.Transactional;

@RunWith(SpringRunner.class)
@ContextConfiguration(classes = HibernateOnH2TestConfig.class)
@Transactional
public class ModeJoinTest {

    @Autowired
    private RootEntityWithJoinFiltersRepository roots;

    @Before
    public void setup() {
        roots.save(RootEntityWithJoinFilters.of(
                LeafEntityWithJoinFilters.of(true, true),
                LeafEntityWithJoinFilters.of(true, false),
                LeafEntityWithJoinFilters.of(false, true),
                LeafEntityWithJoinFilters.of(false, false)
        ));

    }

    @Test
    public void joinPathsAreReused() {

        final var fr = FilterRequest.builder()
                .bool("flag1", f -> f.eq(Boolean.TRUE))
                .bool("flag2", f -> f.eq(Boolean.TRUE))
                .build();
        
        // only one join from rootEntity to leafEntity is supposed to be added
        // otherwise you'd get 4 results from the query generated by the statement below
        Assert.assertEquals(1, roots.findAll(null, fr).size());
    }
}
