package net.optionfactory.spring.data.jpa.filtering.h2.filters.spi.paths;

import net.optionfactory.spring.data.jpa.filtering.FilterRequest;
import net.optionfactory.spring.data.jpa.filtering.h2.HibernateOnH2TestConfig;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.annotation.Transactional;

@SpringJUnitConfig(HibernateOnH2TestConfig.class)
@Transactional
public class ModeJoinTest {

    @Autowired
    private RootEntityWithJoinFiltersRepository roots;

    @BeforeEach
    public void setup() {
        roots.save(RootEntityWithJoinFilters.of(
                LeafEntityWithJoinFilters.of(true, true),
                LeafEntityWithJoinFilters.of(true, false),
                LeafEntityWithJoinFilters.of(false, true),
                LeafEntityWithJoinFilters.of(false, false)
        ));

    }

    @Test
    public void joinPathsAreReused() {

        final var fr = FilterRequest.builder()
                .bool("flag1", f -> f.eq(Boolean.TRUE))
                .bool("flag2", f -> f.eq(Boolean.TRUE))
                .build();
        
        // only one join from rootEntity to leafEntity is supposed to be added
        // otherwise you'd get 4 results from the query generated by the statement below
        Assertions.assertEquals(1, roots.findAll(null, fr).size());
    }
}
