package net.optionfactory.spring.downstream.plugin.emit.ts;

import java.io.File;
import java.io.FileWriter;
import java.lang.reflect.TypeVariable;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.optionfactory.spring.downstream.plugin.emit.SourceEmitter;
import net.optionfactory.spring.downstream.plugin.emit.SourceEmitter.GenerateOutcome;
import net.optionfactory.spring.downstream.plugin.mapping.TypeRegistry;
import net.optionfactory.spring.downstream.plugin.reflection.Reflection;

public class TypeScriptEmitter implements SourceEmitter {

    private final File outputDir;
    private final Map<String, String> translations;
    private final Map<String, String> typeAliases;

    public TypeScriptEmitter(File outputDir, Map<String, String> translations, Map<String, String> typeAliases) {
        this.outputDir = outputDir;
        this.translations = translations;
        this.typeAliases = typeAliases;
    }

    @Override
    public List<GenerateOutcome> emit(TypeRegistry registry) throws Exception {
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }

        final var outcomes = new ArrayList<GenerateOutcome>();
        final var translator = new TypeScriptTypeTranslator(registry, translations, typeAliases);

        final var sortedClasses = registry.allSourceClasses().stream()
                .sorted(Comparator.comparing(c -> c.getPackageName() + c.getSimpleName()))
                .toList();

        final var specFile = new File(outputDir, "spec.d.ts");
        try (final var fw = new FileWriter(specFile, StandardCharsets.UTF_8)) {
            fw.write("// Generated by downstream-maven-plugin\n\n");
            for (final var aliasEntry : typeAliases.entrySet()) {
                final var fqn = aliasEntry.getKey();
                final var simpleName = TypeScriptTypeTranslator.simpleName(fqn);
                fw.write("export type %s = %s;\n".formatted(simpleName, aliasEntry.getValue()));
            }
            if (!typeAliases.isEmpty()) {
                fw.write("\n");
            }
            for (final Class<?> clazz : sortedClasses) {
                final var target = registry.getTargetName(clazz);
                final var tsName = target.flatName();

                final var spec = clazz.isEnum()
                        ? buildEnumSpec(clazz, tsName)
                        : buildDtoSpec(clazz, tsName, translator);

                fw.write(spec);
                fw.write("\n");
                outcomes.add(new GenerateOutcome(tsName, true));
            }
        }

        return outcomes;
    }

    private String buildDtoSpec(Class<?> dtoClass, String name, TypeScriptTypeTranslator translator) {
        final var typeParams = Arrays.stream(dtoClass.getTypeParameters())
                .map(TypeVariable::getName)
                .collect(Collectors.joining(", "));

        final var generic = dtoClass.getTypeParameters().length == 0 ? "" : "<%s>".formatted(typeParams);

        final var fields = Reflection.candidateFields(dtoClass, Object.class);

        final var fbuilder = new StringBuilder();
        for (final var field : fields) {
            final var tsType = translator.translate(field.type());
            final var optional = field.optional() || field.nullable();
            fbuilder.append("    %s%s: %s;\n".formatted(field.name(), optional ? "?" : "", tsType));
        }
        return """
        export interface %s%s {
        %s}
        """.formatted(name, generic, fbuilder.toString());
    }

    private String buildEnumSpec(Class<?> enumClass, String enumName) {
        final var constants = enumClass.getEnumConstants();

        if (constants == null || constants.length == 0) {
            return "export type %s = never;\n".formatted(enumName);
        }
        final var enumValues = Arrays.stream(constants)
                .map(c -> "\"%s\"".formatted(c))
                .collect(Collectors.joining("\n    | "));
        return """
        export type %s = %s;
        """.formatted(enumName, enumValues);
    }

}
